#Diccionarios

In [ ]:
Antonio = {"Antonio" : [9.5,1.76, 20, 1]}

In [ ]:
import pandas as pd

In [ ]:
type (Antonio)

dict

In [ ]:
POO_UP = pd.DataFrame({"Antonio" : [9.5,1.76, 20, 1],
          "Alejandra": [9.2, 1.60, 21, 1],
          "Manuel": [9.2, 1.77, 21, 1],
          "Daniela": [9.3, 1.58, 21, 2],
          "Farca": [9.0, 1.72, 19, 0],
          "Sofía": [9.2, 1.75, 21, 1]}, index = ["Promedio", "Estatura", "Edad", "Hermanos"])

In [ ]:
print(POO_UP)

          Antonio  Alejandra  Manuel  Daniela  Farca  Sofía
Promedio     9.50        9.2    9.20     9.30   9.00   9.20
Estatura     1.76        1.6    1.77     1.58   1.72   1.75
Edad        20.00       21.0   21.00    21.00  19.00  21.00
Hermanos     1.00        1.0    1.00     2.00   0.00   1.00

In [ ]:
#Importamos al módulo pandas
import pandas as pd

In [ ]:
Alumnos = pd.DataFrame(POO_UP)
Alumnos

          Antonio  Alejandra  Manuel  Daniela  Farca  Sofía
Promedio     9.50        9.2    9.20     9.30   9.00   9.20
Estatura     1.76        1.6    1.77     1.58   1.72   1.75
Edad        20.00       21.0   21.00    21.00  19.00  21.00
Hermanos     1.00        1.0    1.00     2.00   0.00   1.00

In [ ]:
type(Alumnos)

pandas.core.frame.DataFrame

In [ ]:
Alumnos.ndim #Dimensión como objeto en Python

2

In [ ]:
#Ingresar a la columna que se llama "Farca"
#df["col i"]
Alumnos["Farca"]

Promedio     9.00
Estatura     1.72
Edad        19.00
Hermanos     0.00
Name: Farca, dtype: float64

In [ ]:
type(Alumnos["Farca"])

pandas.core.series.Series

In [ ]:
#Ingresar por renglones
#.iloc = localizar por índices
Alumnos.iloc[0]

Antonio      9.5
Alejandra    9.2
Manuel       9.2
Daniela      9.3
Farca        9.0
Sofía        9.2
Name: Promedio, dtype: float64

In [ ]:
#Te aparece 1 y 2. Si pones [2:3] te sale solo 2.
Alumnos.iloc[1:3]

          Antonio  Alejandra  Manuel  Daniela  Farca  Sofía
Estatura     1.76        1.6    1.77     1.58   1.72   1.75
Edad        20.00       21.0   21.00    21.00  19.00  21.00

In [ ]:
#Puedo seleccionar las columnas que yo quiera, en este caso Farca y Sofía
Alumnos[["Farca","Sofía"]]

          Farca  Sofía
Promedio   9.00   9.20
Estatura   1.72   1.75
Edad      19.00  21.00
Hermanos   0.00   1.00

In [ ]:
#Seleccionar una columna
Alumnos.iloc[0]

Antonio      9.5
Alejandra    9.2
Manuel       9.2
Daniela      9.3
Farca        9.0
Sofía        9.2
Name: Promedio, dtype: float64

In [ ]:
Alumnos.iloc[1]

Antonio      1.76
Alejandra    1.60
Manuel       1.77
Daniela      1.58
Farca        1.72
Sofía        1.75
Name: Estatura, dtype: float64

In [ ]:
#Rebana la base de datos del primer renglon al segundo
Alumnos.iloc[0:2]

          Antonio  Alejandra  Manuel  Daniela  Farca  Sofía
Promedio     9.50        9.2    9.20     9.30   9.00   9.20
Estatura     1.76        1.6    1.77     1.58   1.72   1.75